# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/dx4bdrs7mq3jfviqhszrc7l35ps9kg64-cmake-3.31.7/bin/cmake

# The command to remove a file.
RM = /nix/store/dx4bdrs7mq3jfviqhszrc7l35ps9kg64-cmake-3.31.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/cxb/cxb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/cxb/cxb/build/coverage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/nix/store/dx4bdrs7mq3jfviqhszrc7l35ps9kg64-cmake-3.31.7/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/dx4bdrs7mq3jfviqhszrc7l35ps9kg64-cmake-3.31.7/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/dx4bdrs7mq3jfviqhszrc7l35ps9kg64-cmake-3.31.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/cxb/cxb/build/coverage/CMakeFiles /home/runner/work/cxb/cxb/build/coverage//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/cxb/cxb/build/coverage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_array

# Build rule for target.
test_array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_array
.PHONY : test_array

# fast build rule for target.
test_array/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array.dir/build.make CMakeFiles/test_array.dir/build
.PHONY : test_array/fast

#=============================================================================
# Target rules for targets named test_string

# Build rule for target.
test_string: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_string
.PHONY : test_string

# fast build rule for target.
test_string/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_string.dir/build.make CMakeFiles/test_string.dir/build
.PHONY : test_string/fast

#=============================================================================
# Target rules for targets named test_arena

# Build rule for target.
test_arena: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_arena
.PHONY : test_arena

# fast build rule for target.
test_arena/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/build
.PHONY : test_arena/fast

#=============================================================================
# Target rules for targets named test_hm

# Build rule for target.
test_hm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hm
.PHONY : test_hm

# fast build rule for target.
test_hm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hm.dir/build.make CMakeFiles/test_hm.dir/build
.PHONY : test_hm/fast

#=============================================================================
# Target rules for targets named bench_string

# Build rule for target.
bench_string: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_string
.PHONY : bench_string

# fast build rule for target.
bench_string/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string.dir/build.make CMakeFiles/bench_string.dir/build
.PHONY : bench_string/fast

#=============================================================================
# Target rules for targets named bench_string_header

# Build rule for target.
bench_string_header: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_string_header
.PHONY : bench_string_header

# fast build rule for target.
bench_string_header/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string_header.dir/build.make CMakeFiles/bench_string_header.dir/build
.PHONY : bench_string_header/fast

#=============================================================================
# Target rules for targets named bench_std_headers

# Build rule for target.
bench_std_headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_std_headers
.PHONY : bench_std_headers

# fast build rule for target.
bench_std_headers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_std_headers.dir/build.make CMakeFiles/bench_std_headers.dir/build
.PHONY : bench_std_headers/fast

#=============================================================================
# Target rules for targets named bench_hm

# Build rule for target.
bench_hm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_hm
.PHONY : bench_hm

# fast build rule for target.
bench_hm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_hm.dir/build.make CMakeFiles/bench_hm.dir/build
.PHONY : bench_hm/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f deps/Catch2/src/CMakeFiles/Catch2.dir/build.make deps/Catch2/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f deps/Catch2/src/CMakeFiles/Catch2WithMain.dir/build.make deps/Catch2/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

cxb/cxb.o: cxb/cxb.cpp.o
.PHONY : cxb/cxb.o

# target to build an object file
cxb/cxb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array.dir/build.make CMakeFiles/test_array.dir/cxb/cxb.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_string.dir/build.make CMakeFiles/test_string.dir/cxb/cxb.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/cxb/cxb.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hm.dir/build.make CMakeFiles/test_hm.dir/cxb/cxb.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string.dir/build.make CMakeFiles/bench_string.dir/cxb/cxb.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string_header.dir/build.make CMakeFiles/bench_string_header.dir/cxb/cxb.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_std_headers.dir/build.make CMakeFiles/bench_std_headers.dir/cxb/cxb.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_hm.dir/build.make CMakeFiles/bench_hm.dir/cxb/cxb.cpp.o
.PHONY : cxb/cxb.cpp.o

cxb/cxb.i: cxb/cxb.cpp.i
.PHONY : cxb/cxb.i

# target to preprocess a source file
cxb/cxb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array.dir/build.make CMakeFiles/test_array.dir/cxb/cxb.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_string.dir/build.make CMakeFiles/test_string.dir/cxb/cxb.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/cxb/cxb.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hm.dir/build.make CMakeFiles/test_hm.dir/cxb/cxb.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string.dir/build.make CMakeFiles/bench_string.dir/cxb/cxb.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string_header.dir/build.make CMakeFiles/bench_string_header.dir/cxb/cxb.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_std_headers.dir/build.make CMakeFiles/bench_std_headers.dir/cxb/cxb.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_hm.dir/build.make CMakeFiles/bench_hm.dir/cxb/cxb.cpp.i
.PHONY : cxb/cxb.cpp.i

cxb/cxb.s: cxb/cxb.cpp.s
.PHONY : cxb/cxb.s

# target to generate assembly for a file
cxb/cxb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array.dir/build.make CMakeFiles/test_array.dir/cxb/cxb.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_string.dir/build.make CMakeFiles/test_string.dir/cxb/cxb.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/cxb/cxb.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hm.dir/build.make CMakeFiles/test_hm.dir/cxb/cxb.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string.dir/build.make CMakeFiles/bench_string.dir/cxb/cxb.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string_header.dir/build.make CMakeFiles/bench_string_header.dir/cxb/cxb.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_std_headers.dir/build.make CMakeFiles/bench_std_headers.dir/cxb/cxb.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_hm.dir/build.make CMakeFiles/bench_hm.dir/cxb/cxb.cpp.s
.PHONY : cxb/cxb.cpp.s

tests/benchmarks/bench_hm.o: tests/benchmarks/bench_hm.cpp.o
.PHONY : tests/benchmarks/bench_hm.o

# target to build an object file
tests/benchmarks/bench_hm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_hm.dir/build.make CMakeFiles/bench_hm.dir/tests/benchmarks/bench_hm.cpp.o
.PHONY : tests/benchmarks/bench_hm.cpp.o

tests/benchmarks/bench_hm.i: tests/benchmarks/bench_hm.cpp.i
.PHONY : tests/benchmarks/bench_hm.i

# target to preprocess a source file
tests/benchmarks/bench_hm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_hm.dir/build.make CMakeFiles/bench_hm.dir/tests/benchmarks/bench_hm.cpp.i
.PHONY : tests/benchmarks/bench_hm.cpp.i

tests/benchmarks/bench_hm.s: tests/benchmarks/bench_hm.cpp.s
.PHONY : tests/benchmarks/bench_hm.s

# target to generate assembly for a file
tests/benchmarks/bench_hm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_hm.dir/build.make CMakeFiles/bench_hm.dir/tests/benchmarks/bench_hm.cpp.s
.PHONY : tests/benchmarks/bench_hm.cpp.s

tests/benchmarks/bench_std_headers.o: tests/benchmarks/bench_std_headers.cpp.o
.PHONY : tests/benchmarks/bench_std_headers.o

# target to build an object file
tests/benchmarks/bench_std_headers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_std_headers.dir/build.make CMakeFiles/bench_std_headers.dir/tests/benchmarks/bench_std_headers.cpp.o
.PHONY : tests/benchmarks/bench_std_headers.cpp.o

tests/benchmarks/bench_std_headers.i: tests/benchmarks/bench_std_headers.cpp.i
.PHONY : tests/benchmarks/bench_std_headers.i

# target to preprocess a source file
tests/benchmarks/bench_std_headers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_std_headers.dir/build.make CMakeFiles/bench_std_headers.dir/tests/benchmarks/bench_std_headers.cpp.i
.PHONY : tests/benchmarks/bench_std_headers.cpp.i

tests/benchmarks/bench_std_headers.s: tests/benchmarks/bench_std_headers.cpp.s
.PHONY : tests/benchmarks/bench_std_headers.s

# target to generate assembly for a file
tests/benchmarks/bench_std_headers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_std_headers.dir/build.make CMakeFiles/bench_std_headers.dir/tests/benchmarks/bench_std_headers.cpp.s
.PHONY : tests/benchmarks/bench_std_headers.cpp.s

tests/benchmarks/bench_string.o: tests/benchmarks/bench_string.cpp.o
.PHONY : tests/benchmarks/bench_string.o

# target to build an object file
tests/benchmarks/bench_string.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string.dir/build.make CMakeFiles/bench_string.dir/tests/benchmarks/bench_string.cpp.o
.PHONY : tests/benchmarks/bench_string.cpp.o

tests/benchmarks/bench_string.i: tests/benchmarks/bench_string.cpp.i
.PHONY : tests/benchmarks/bench_string.i

# target to preprocess a source file
tests/benchmarks/bench_string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string.dir/build.make CMakeFiles/bench_string.dir/tests/benchmarks/bench_string.cpp.i
.PHONY : tests/benchmarks/bench_string.cpp.i

tests/benchmarks/bench_string.s: tests/benchmarks/bench_string.cpp.s
.PHONY : tests/benchmarks/bench_string.s

# target to generate assembly for a file
tests/benchmarks/bench_string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string.dir/build.make CMakeFiles/bench_string.dir/tests/benchmarks/bench_string.cpp.s
.PHONY : tests/benchmarks/bench_string.cpp.s

tests/benchmarks/bench_string_header.o: tests/benchmarks/bench_string_header.cpp.o
.PHONY : tests/benchmarks/bench_string_header.o

# target to build an object file
tests/benchmarks/bench_string_header.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string_header.dir/build.make CMakeFiles/bench_string_header.dir/tests/benchmarks/bench_string_header.cpp.o
.PHONY : tests/benchmarks/bench_string_header.cpp.o

tests/benchmarks/bench_string_header.i: tests/benchmarks/bench_string_header.cpp.i
.PHONY : tests/benchmarks/bench_string_header.i

# target to preprocess a source file
tests/benchmarks/bench_string_header.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string_header.dir/build.make CMakeFiles/bench_string_header.dir/tests/benchmarks/bench_string_header.cpp.i
.PHONY : tests/benchmarks/bench_string_header.cpp.i

tests/benchmarks/bench_string_header.s: tests/benchmarks/bench_string_header.cpp.s
.PHONY : tests/benchmarks/bench_string_header.s

# target to generate assembly for a file
tests/benchmarks/bench_string_header.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_string_header.dir/build.make CMakeFiles/bench_string_header.dir/tests/benchmarks/bench_string_header.cpp.s
.PHONY : tests/benchmarks/bench_string_header.cpp.s

tests/test_arena.o: tests/test_arena.cpp.o
.PHONY : tests/test_arena.o

# target to build an object file
tests/test_arena.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/tests/test_arena.cpp.o
.PHONY : tests/test_arena.cpp.o

tests/test_arena.i: tests/test_arena.cpp.i
.PHONY : tests/test_arena.i

# target to preprocess a source file
tests/test_arena.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/tests/test_arena.cpp.i
.PHONY : tests/test_arena.cpp.i

tests/test_arena.s: tests/test_arena.cpp.s
.PHONY : tests/test_arena.s

# target to generate assembly for a file
tests/test_arena.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/tests/test_arena.cpp.s
.PHONY : tests/test_arena.cpp.s

tests/test_array.o: tests/test_array.cpp.o
.PHONY : tests/test_array.o

# target to build an object file
tests/test_array.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array.dir/build.make CMakeFiles/test_array.dir/tests/test_array.cpp.o
.PHONY : tests/test_array.cpp.o

tests/test_array.i: tests/test_array.cpp.i
.PHONY : tests/test_array.i

# target to preprocess a source file
tests/test_array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array.dir/build.make CMakeFiles/test_array.dir/tests/test_array.cpp.i
.PHONY : tests/test_array.cpp.i

tests/test_array.s: tests/test_array.cpp.s
.PHONY : tests/test_array.s

# target to generate assembly for a file
tests/test_array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_array.dir/build.make CMakeFiles/test_array.dir/tests/test_array.cpp.s
.PHONY : tests/test_array.cpp.s

tests/test_hm.o: tests/test_hm.cpp.o
.PHONY : tests/test_hm.o

# target to build an object file
tests/test_hm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hm.dir/build.make CMakeFiles/test_hm.dir/tests/test_hm.cpp.o
.PHONY : tests/test_hm.cpp.o

tests/test_hm.i: tests/test_hm.cpp.i
.PHONY : tests/test_hm.i

# target to preprocess a source file
tests/test_hm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hm.dir/build.make CMakeFiles/test_hm.dir/tests/test_hm.cpp.i
.PHONY : tests/test_hm.cpp.i

tests/test_hm.s: tests/test_hm.cpp.s
.PHONY : tests/test_hm.s

# target to generate assembly for a file
tests/test_hm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hm.dir/build.make CMakeFiles/test_hm.dir/tests/test_hm.cpp.s
.PHONY : tests/test_hm.cpp.s

tests/test_string.o: tests/test_string.cpp.o
.PHONY : tests/test_string.o

# target to build an object file
tests/test_string.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_string.dir/build.make CMakeFiles/test_string.dir/tests/test_string.cpp.o
.PHONY : tests/test_string.cpp.o

tests/test_string.i: tests/test_string.cpp.i
.PHONY : tests/test_string.i

# target to preprocess a source file
tests/test_string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_string.dir/build.make CMakeFiles/test_string.dir/tests/test_string.cpp.i
.PHONY : tests/test_string.cpp.i

tests/test_string.s: tests/test_string.cpp.s
.PHONY : tests/test_string.s

# target to generate assembly for a file
tests/test_string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_string.dir/build.make CMakeFiles/test_string.dir/tests/test_string.cpp.s
.PHONY : tests/test_string.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... bench_hm"
	@echo "... bench_std_headers"
	@echo "... bench_string"
	@echo "... bench_string_header"
	@echo "... test_arena"
	@echo "... test_array"
	@echo "... test_hm"
	@echo "... test_string"
	@echo "... cxb/cxb.o"
	@echo "... cxb/cxb.i"
	@echo "... cxb/cxb.s"
	@echo "... tests/benchmarks/bench_hm.o"
	@echo "... tests/benchmarks/bench_hm.i"
	@echo "... tests/benchmarks/bench_hm.s"
	@echo "... tests/benchmarks/bench_std_headers.o"
	@echo "... tests/benchmarks/bench_std_headers.i"
	@echo "... tests/benchmarks/bench_std_headers.s"
	@echo "... tests/benchmarks/bench_string.o"
	@echo "... tests/benchmarks/bench_string.i"
	@echo "... tests/benchmarks/bench_string.s"
	@echo "... tests/benchmarks/bench_string_header.o"
	@echo "... tests/benchmarks/bench_string_header.i"
	@echo "... tests/benchmarks/bench_string_header.s"
	@echo "... tests/test_arena.o"
	@echo "... tests/test_arena.i"
	@echo "... tests/test_arena.s"
	@echo "... tests/test_array.o"
	@echo "... tests/test_array.i"
	@echo "... tests/test_array.s"
	@echo "... tests/test_hm.o"
	@echo "... tests/test_hm.i"
	@echo "... tests/test_hm.s"
	@echo "... tests/test_string.o"
	@echo "... tests/test_string.i"
	@echo "... tests/test_string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

