name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check formatting
        run: |
          nix develop ./ci --command bash -c "./scripts/format.sh --check"

  build-test:
    name: Build & Test (${{ matrix.compiler }} ${{ matrix.build_type }} ${{ matrix.os }})
    needs: format
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build & Test
        env:
          COMPILER: ${{ matrix.compiler }}
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          nix develop ./ci --command bash ./ci/ci.sh
