name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    name: Build & Test ${{ matrix.nix_system }} ${{ matrix.compiler }} ${{ matrix.build_type }} (${{ matrix.os }})
    # All jobs run in parallel; format check runs conditionally within this job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
        compiler: [gcc, clang]
        build_type: [Debug, Release]
        include:
          - os: ubuntu-22.04
            nix_system: x86_64-linux
          # TODO: use ubuntu-22.04-arm once repo is public
          - os: ubuntu-22.04
            nix_system: aarch64-linux
          - os: macos-14
            nix_system: x86_64-darwin
          - os: macos-14
            nix_system: aarch64-darwin
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check formatting
        if: matrix.os == 'ubuntu-22.04' && matrix.compiler == 'clang' && matrix.build_type == 'Debug' && matrix.nix_system == 'x86_64-linux'
        run: |
          nix develop ./ci --system ${{ matrix.nix_system }} --command bash -c "./scripts/format.sh --check"
      - name: Build & Test
        env:
          COMPILER: ${{ matrix.compiler }}
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          nix develop ./ci --system ${{ matrix.nix_system }} --command bash ./ci/ci.sh
