name: CI (Nix)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  nix-ci:
    name: Nix Build, Format & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4

      # Install Nix on the runner
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check formatting
        run: |
          nix develop ./ci --command bash -c "./scripts/format.sh --check"

      - name: Build & Test (${{ matrix.compiler }} ${{ matrix.build_type }})
        env:
          COMPILER: ${{ matrix.compiler }}
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          nix develop ./ci --command bash ./ci/ci.sh
