#!/bin/bash

# To install: 
# cp scripts/hooks/pre-commit .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit

YELLOW='\033[1;33m'

set -e
echo -e "${YELLOW}Running pre-commit format check...${NC}"
./scripts/format.sh --check
